<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SpellEditor</RootNamespace>
    <AssemblyName>SpellEditor</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowedReferenceRelatedFileExtensions>.pdb</AllowedReferenceRelatedFileExtensions>
    <NoWarn>$(NoWarn);CA1416;SYSLIB0014</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="Resources\**\*.xaml" />
    <None Remove="Resources\**\*.xaml" />
    <None Remove="icon.ico" />
    <None Remove="Sources\Controls\SpellFamilyNames\icon.ico" />
    <Resource Include="icon.ico" />
    <Resource Include="Sources\Controls\SpellFamilyNames\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.2.0" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SereniaBLPLib\SereniaBLPLib.csproj" />
    <ProjectReference Include="..\StormLibSharp\StormLibSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Documentation\**\*">
      <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
